In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./dubai_spots_clean.csv")

In [3]:
df

,name,lat,lng,type,rating,opening_time,closing_time
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00

In [4]:
Ps = pd.read_csv("./dubai_areas.csv")

In [5]:
Ps

            area_name emoji     lat     lng
0      Downtown Dubai    🏙️  25.200  55.300
1      Jumeirah Beach     🌊  25.205  55.260
2        Business Bay     🏢  25.185  55.310
3           City Walk    🛍️  25.210  55.270
4             Al Safa     🕌  25.175  55.255
5   Sheikh Zayed Road     🌆  25.220  55.290
6                DIFC     🏨  25.215  55.285
7         Zabeel Park     🌳  25.230  55.320
8             Al Wasl     🏫  25.190  55.340
9           Oud Metha     🏪  25.240  55.315
10        Al Jafiliya     🚇  25.245  55.295
11        Al Mankhool    🏘️  25.165  55.305
12            Al Bada     🌴  25.155  55.330
13              Satwa     🏬  25.175  55.275

In [6]:
Ps['label'] =  Ps['emoji'] + "  " + Ps['area_name']
Ps

            area_name emoji     lat     lng                 label
0      Downtown Dubai    🏙️  25.200  55.300    🏙️  Downtown Dubai
1      Jumeirah Beach     🌊  25.205  55.260     🌊  Jumeirah Beach
2        Business Bay     🏢  25.185  55.310       🏢  Business Bay
3           City Walk    🛍️  25.210  55.270         🛍️  City Walk
4             Al Safa     🕌  25.175  55.255            🕌  Al Safa
5   Sheikh Zayed Road     🌆  25.220  55.290  🌆  Sheikh Zayed Road
6                DIFC     🏨  25.215  55.285               🏨  DIFC
7         Zabeel Park     🌳  25.230  55.320        🌳  Zabeel Park
8             Al Wasl     🏫  25.190  55.340            🏫  Al Wasl
9           Oud Metha     🏪  25.240  55.315          🏪  Oud Metha
10        Al Jafiliya     🚇  25.245  55.295        🚇  Al Jafiliya
11        Al Mankhool    🏘️  25.165  55.305       🏘️  Al Mankhool
12            Al Bada     🌴  25.155  55.330            🌴  Al Bada
13              Satwa     🏬  25.175  55.275              🏬  Satwa

In [7]:
Ps.to_csv("dubai_areas_labels.csv")

In [8]:
Ps[Ps["label"]=="🏨 DIFC"]

Empty DataFrame
Columns: [area_name, emoji, lat, lng, label]
Index: []

In [9]:
df[df['type'] == "cart"]

,name,lat,lng,type,rating,opening_time,closing_time
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00

In [10]:
from geopy.distance import geodesic
user_location = (25.175,55.275)
spot_location = (25.179104,55.348576)
geodesic(user_location,spot_location).km

7.430744833854102

In [11]:
def  calucalate_distance(row):
    lat = row['lat']
    lng = row['lng']
    spot_location=lat,lng
    dis = geodesic(user_location,spot_location).km
    return(dis,2)
def get_row(row):
    return calucalate_distance
df["distance_km"] = df.apply(calucalate_distance,axis=1)

In [12]:
from datetime import datetime

def is_open_spot(row):
    
        now = datetime.now().strftime()

        open_t = row["opening_time"]
        close_t = row["closing_time"]

        
        if open_t <= now <= close_t :
              return"open"
        
        else:
            return "closed"

In [13]:
df

,name,lat,lng,type,rating,opening_time,closing_time,distance_km
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00,"(3.954689737613209, 2)"
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00,"(8.563451129399372, 2)"
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00,"(3.2225461138672973, 2)"
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00,"(8.617456919127429, 2)"
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00,"(7.019766657869005, 2)"
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00,"(2.2257915344825383, 2)"
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00,"(1.8950518626145192, 2)"
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00,"(6.479926075800066, 2)"
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00,"(6.330717923510119, 2)"
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00,"(7.917924561617801, 2)"
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00,"(8.543900558233457, 2)"
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00,"(8.62097361065093, 2)"
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00,"(5.2302435454468625, 2)"
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00,"(3.6033043929248234, 2)"
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00,"(3.692990048638637, 2)"
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00,"(4.301689598964106, 2)"
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00,"(5.939979958763272, 2)"
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00,"(8.447319893024325, 2)"
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00,"(5.2104189774331005, 2)"
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00,"(7.430744833854102, 2)"
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00,"(2.29410891797536, 2)"
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00,"(4.806834510219426, 2)"
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00,"(1.875744479717079, 2)"
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00,"(2.2068588696929594, 2)"
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00,"(3.545659226948698, 2)"
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00,"(6.458944644141507, 2)"
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00,"(7.824464287342759, 2)"
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00,"(4.1792049484758875, 2)"
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00,"(7.7933192946677785, 2)"
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00,"(6.260863315203477, 2)"
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00,"(5.258764852652561, 2)"
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00,"(3.994996085480573, 2)"
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00,"(9.531432883973851, 2)"
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00,"(4.3759561743991195, 2)"
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00,"(4.804201731632804, 2)"
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00,"(7.525611023121286, 2)"
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00,"(4.6298017793826185, 2)"
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00,"(0.4780367338944854, 2)"
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00,"(6.230275325671434, 2)"
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00,"(6.975233480643273, 2)"
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00,"(8.177104304463658, 2)"
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00,"(7.149678274650039, 2)"
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00,"(8.170000624619457, 2)"
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00,"(4.174079568540523, 2)"
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00,"(9.70603221199157, 2)"
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00,"(8.078286867907694, 2)"
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00,"(2.1509848437629673, 2)"
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00,"(7.699464797389367, 2)"
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00,"(0.6341050449636959, 2)"
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00,"(4.320259835189676, 2)"

In [14]:
df.sort_values(by="distance_km")

,name,lat,lng,type,rating,opening_time,closing_time,distance_km
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00,"(0.4780367338944854, 2)"
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00,"(0.6341050449636959, 2)"
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00,"(1.875744479717079, 2)"
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00,"(1.8950518626145192, 2)"
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00,"(2.1509848437629673, 2)"
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00,"(2.2068588696929594, 2)"
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00,"(2.2257915344825383, 2)"
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00,"(2.29410891797536, 2)"
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00,"(3.2225461138672973, 2)"
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00,"(3.545659226948698, 2)"
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00,"(3.6033043929248234, 2)"
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00,"(3.692990048638637, 2)"
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00,"(3.954689737613209, 2)"
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00,"(3.994996085480573, 2)"
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00,"(4.174079568540523, 2)"
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00,"(4.1792049484758875, 2)"
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00,"(4.301689598964106, 2)"
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00,"(4.320259835189676, 2)"
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00,"(4.3759561743991195, 2)"
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00,"(4.6298017793826185, 2)"
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00,"(4.804201731632804, 2)"
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00,"(4.806834510219426, 2)"
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00,"(5.2104189774331005, 2)"
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00,"(5.2302435454468625, 2)"
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00,"(5.258764852652561, 2)"
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00,"(5.939979958763272, 2)"
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00,"(6.230275325671434, 2)"
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00,"(6.260863315203477, 2)"
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00,"(6.330717923510119, 2)"
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00,"(6.458944644141507, 2)"
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00,"(6.479926075800066, 2)"
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00,"(6.975233480643273, 2)"
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00,"(7.019766657869005, 2)"
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00,"(7.149678274650039, 2)"
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00,"(7.430744833854102, 2)"
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00,"(7.525611023121286, 2)"
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00,"(7.699464797389367, 2)"
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00,"(7.7933192946677785, 2)"
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00,"(7.824464287342759, 2)"
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00,"(7.917924561617801, 2)"
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00,"(8.078286867907694, 2)"
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00,"(8.170000624619457, 2)"
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00,"(8.177104304463658, 2)"
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00,"(8.447319893024325, 2)"
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00,"(8.543900558233457, 2)"
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00,"(8.563451129399372, 2)"
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00,"(8.617456919127429, 2)"
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00,"(8.62097361065093, 2)"
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00,"(9.531432883973851, 2)"
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00,"(9.70603221199157, 2)"

In [15]:
df.sort_values(by="rating",ascending=False)

,name,lat,lng,type,rating,opening_time,closing_time,distance_km
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00,"(7.149678274650039, 2)"
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00,"(4.1792049484758875, 2)"
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00,"(1.8950518626145192, 2)"
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00,"(7.7933192946677785, 2)"
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00,"(4.3759561743991195, 2)"
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00,"(0.4780367338944854, 2)"
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00,"(3.994996085480573, 2)"
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00,"(3.2225461138672973, 2)"
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00,"(7.019766657869005, 2)"
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00,"(2.2257915344825383, 2)"
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00,"(6.230275325671434, 2)"
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00,"(4.804201731632804, 2)"
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00,"(5.939979958763272, 2)"
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00,"(8.563451129399372, 2)"
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00,"(0.6341050449636959, 2)"
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00,"(9.70603221199157, 2)"
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00,"(1.875744479717079, 2)"
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00,"(4.301689598964106, 2)"
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00,"(3.6033043929248234, 2)"
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00,"(6.458944644141507, 2)"
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00,"(7.699464797389367, 2)"
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00,"(6.975233480643273, 2)"
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00,"(3.545659226948698, 2)"
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00,"(9.531432883973851, 2)"
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00,"(8.177104304463658, 2)"
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00,"(4.806834510219426, 2)"
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00,"(6.260863315203477, 2)"
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00,"(5.258764852652561, 2)"
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00,"(7.917924561617801, 2)"
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00,"(3.954689737613209, 2)"
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00,"(2.1509848437629673, 2)"
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00,"(6.479926075800066, 2)"
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00,"(5.2302435454468625, 2)"
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00,"(6.330717923510119, 2)"
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00,"(4.320259835189676, 2)"
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00,"(4.174079568540523, 2)"
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00,"(8.078286867907694, 2)"
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00,"(2.29410891797536, 2)"
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00,"(8.543900558233457, 2)"
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00,"(7.430744833854102, 2)"
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00,"(2.2068588696929594, 2)"
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00,"(8.170000624619457, 2)"
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00,"(7.525611023121286, 2)"
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00,"(7.824464287342759, 2)"
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00,"(8.617456919127429, 2)"
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00,"(3.692990048638637, 2)"
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00,"(4.6298017793826185, 2)"
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00,"(8.447319893024325, 2)"
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00,"(8.62097361065093, 2)"
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00,"(5.2104189774331005, 2)"

In [20]:
row = df.iloc[0:2]
for ind,rows in row.iterrows():
    print(rows["name"],rows["type"],rows["distance_km"])

Brewed Awakening cart (3.954689737613209, 2)
Chill & Spill truck (8.563451129399372, 2)